name: Update branch with updated submodule on libjxl

on:
  pull_request:
    types: [opened, reopened, synchronize]
    
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 'Cloning libjxl'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: mo271/libjxl
          path: libjxl
          submodules: recursive

      - name: Pull & update highway
        run: |
          cd libjxl/third_party/
          git fetch origin
          git checkout origin/master
          cd ../../

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update highway submodule" || echo "No changes to commit"
          git push HEAD:main_with_highway
