name: trigger libjxl workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/mo271/libjxl/dispatches \
               -u ${{ secrets.TOKEN }} \
               -d '{"event_type":"higway_test"}'
      - uses: actions/checkout@v3
